name: Testing-Debug-Clang
on: [push]

jobs:
  test-app-clang-debug:
    runs-on: ubuntu-latest
    env:
      TESTING: 1
      CLANG: 1

    steps:
      - uses: actions/checkout@v3

      - name: install clang
        run: sudo apt install clang-15 --install-suggests

      - name: install cmake
        run: sudo apt install -y cmake

      - name: install zmq
        run: sudo apt install -y libzmq3-dev

      - name: build cmake
        working-directory: ./src
        run: |
          mkdir build && cd build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ..
          make -j2

# currently broken
#      - name: run test
#        working-directory: ./src/build
#        run: ./annadb_driver
